name: diary
base: core22
version: '1.0.0'
summary: A desktop application to manage diaries via Nextcloud
description: |
  Diary is a Linux-centric desktop application written in Go
  that integrates with the Nextcloud diary app. It allows users
  to manage diary entries securely and efficiently.

grade: stable
confinement: strict
license: MIT
icon: snap/local/diary.png
contact: https://github.com/kz6fittycent/diary
issues: https://github.com/kz6fittycent/diary/issues
source-code: https://github.com/kz6fittycent/diary
donation: https://www.patreon.com/kz6fittycent

parts:
  diary:
    plugin: python
    source: https://github.com/kz6fittycent/diary
    source-type: git
    python-packages:
      - PyQt5
      - requests
    stage-packages:
      - libglib2.0-0
      - libgdk-pixbuf2.0-0
      - libcairo2
      - libpango1.0-0
      - libatk1.0-0
      - libgtk-3-0
      - libnss3

apps:
  diary:
    command: bin/main.py
    plugs:
      - network
      - network-bind
      - home
      
