name: diary
base: core22
version: '1.0.0'
summary: A desktop application to manage diaries via Nextcloud
description: |
  Diary is a Linux-centric desktop application written in Go
  that integrates with the Nextcloud diary app. It allows users
  to manage diary entries securely and efficiently, with support
  for offline mode and HTTPS security.

grade: stable
confinement: strict

parts:
  diary:
    plugin: nil
    source: https://github.com/kz6fittycent/diary
    source-type: git
    build-packages:
      - wget
      - tar
      - libgtk-3-dev
      - libxxf86vm1
    stage-packages:
      - libglib2.0-0
      - libgdk-pixbuf2.0-0
      - libcairo2
      - libpango1.0-0
      - libatk1.0-0
      - libgtk-3-0
      - libnss3
      - libxxf86vm1
      
    override-build: |
      # Specify the Go version
      GO_VERSION=1.20.6
      wget -q https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz
      tar -C /usr/local -xzf go${GO_VERSION}.linux-amd64.tar.gz
      export PATH=/usr/local/go/bin:$PATH
      
      # Verify Go version
      go version
      
      # Build the application
      go mod tidy
      go build -o $CRAFT_PART_INSTALL/diary

apps:
  diary:
    command: diary
    extensions: 
      - gnome
    plugs:
      - network  
      - network-bind  
      - home
